CREATE DATABASE ACADSYS;
USE ACADSYS;

CREATE TABLE cadastro_alunos (

  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  matricula VARCHAR(20) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  curso VARCHAR(100) NOT NULL,
  materias VARCHAR(200) NOT NULL
  
);

CREATE TABLE cadastro_prof (

  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  matricula VARCHAR(20) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  materias VARCHAR(200) NOT NULL
  
);
